Application/config/routes.rb
Rails.application.routes.draw do
  get "/mem_profile", to: "members#show"
  get "/edit_mem", to: "members#edit"
  delete "/delete_member", to: "members#destroy"
  delete "remove_member/:id", to: "users#remove_member", as: "remove_member"
  resources :members
  resources :products

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get "/", to: "articles#index"

  get "/add_potential_members", to: "users#add_members"
  post "/create_new_member", to: "users#create_new_member"
  get "/signup_organization", to: "users#new"
  get "/signup_member", to: "members#new"

  post "add_to_cart/:product_id", to: "products#add_to_cart", as: 'add_to_cart'

  delete "remove_from_cart/:product_id", to: "products#remove_from_cart", as: 'remove_from_cart'

  get "view_cart", to: "products#view_cart", as: 'view_cart'

  post '/set_referral', to: "products#set_referral"

  post "/tag_marketplace", to: "products#tag_marketplace"

  post "/org_marketplace", to: "products#org_marketplace"

  post "/marketplace", to: "products#tag_marketplace"

  resources :users, only: [:new, :create, :update, :edit, :destroy, :show, :index]

  get "/welcome", to: "articles#welcome"

  get "/marketplace", to: "products#marketplace"

  root to: "products#marketplace"

  get "/dashboard", to: "dashboards#dashboard"

  get "products", to: "articles#products"
  get "/view_members", to: "users#index"
  get "profile", to: "dashboards#dashboard"
  

  get "/checkout", to: "orders#index"

  get "upload", to: "products#new"
  post "upload", to: "products#create"

  get 'editprofile', to: "users#edit"

  delete 'deleteprofile', to: "users#destroy"
  delete '/', to: "sessions#destroy"

  post :create_order, :to => 'orders#create_order'
  post :capture_order, :to => 'orders#capture_order'

  get 'tags/:tag', to: 'products#tag_index', as: :tag

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get '/auth/google_oauth2_member/callback' => 'sessions#omniauth_member'
  get '/auth/failure', to: redirect('/')



  resources :articles
  resources :member
  # post "/login", to: "articles#welcome"

  # post "userinfo", to: ""
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Application/app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password 
    has_many :products, dependent: :destroy
    has_many :members
    # validates :username, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
    def self.from_omniauth(auth)
        where(username: auth.info.email).first_or_initialize do |user|
            user.first = auth.info.name
            user.username = auth.info.email
            user.password = SecureRandom.hex
        end
    end
end

Application/app/controllers/users_controller.rb
class UsersController < ApplicationController
    # skip_before_action :verify_authenticity_token
    before_action :logged_in_user, only: [:edit, :update, :show]
    # before_action :correct_user,   only: [:edit, :update, :show]

    def new
        @user = User.new
    end

    def index
        @user = User.find_by_id(session[:id])
        @members = Member.where(users_id: @user.id)
    end

    def remove_member
        @member = Member.find_by_id(params[:id])
        @member.update_attribute(:users_id, nil)

        respond_to do |format|
            format.html { redirect_to "/view_members", notice: "Member was removed from organization." }
            format.json { head :no_content }
        end
    end

    def add_members
    end

    def create_new_member
        @user = User.find_by_id(session[:id])
        if Member.exists?(username: params[:username])
            @member = Member.find_by_username(params[:username])
            @member.update_attribute(:users_id, @user.id)
            flash[:notice] = "User " + @member.first + " " + @member.last +  " was added to the organization."
        else
            flash[:notice] = "User does not exist." 
        end


        respond_to do |format|
            format.html { 
                if Member.exists?(username: params[:username]) 
                    redirect_to "/add_potential_members", notice: "User " + @member.first + " " + @member.last +  " was added to the organization."
                else
                    redirect_to "/add_potential_members", notice: "User does not exist."
                end
            }
            format.json { head :no_content }
        end
    end

        
    def create
        @user = User.new(user_params)
        if /\A[^@\s]+@[^@\s]+\z/.match(@user.username) == nil 
            flash[:notice] = "Invalid Username"
            redirect_to '/signup_organization'
        elsif User.find_by(username: @user.username)
            flash[:notice] = "Username already exists"
            redirect_to '/signup_organization'
        elsif @user.password.length < 8
            flash[:notice] = "Password length should be 8 or longer."
            redirect_to '/signup_organization'
        else @user.valid?
            @user = User.create(params.require(:user).permit(:first, :username, :password))
            session[:id] = @user.id
            session[:type] = "organization"
            redirect_to '/profile'
        end
    end

    def edit
        @user = User.find_by_id(session[:id])
    end

    def update
        @user = User.find_by_id(session[:id])
        # user_params = params.require(:user).permit(:username, :password, :first, :last)
        @user.assign_attributes(params.require(:user).permit(:first, :last, :username, :password))
        if @user.changed?
            if @user.save
                flash[:success] = true
            end
        end
        redirect_to '/profile'
    end

    def destroy
        @user = User.find_by_id(session[:id])
        Member.where(users_id: @user.id).update_all(users_id: nil)
        # @members.update_all(:users_id, nil)
        @user.destroy
        flash[:notice] = "User '#{@user.first}' deleted."
        redirect_to '/'
    end
    
    def show 
        @user = User.find_by_id(session[:id])
    end

    def user_params
        params.require(:user).permit(:first, :last, :username, :password)
    end

    def logged_in_user  
        unless logged_in?
          flash[:danger] = "Please log in."
          redirect_to sign_in_url
        end
    end
end 

Application/app/views/users/add_members.html.erb
<div id="members">
  <div id="bkbtn">
    <%= link_to '< Back', dashboard_path %>
  </div>
  <p id="notice"><%= notice %></p>

  <h1>Add Members</h1>

  <%= simple_form_for :add_members, :url => "/create_new_member", :method => :post do |f| %>
    <%= f.input :username, input_html: { name: "username" } %>
    <%= f.button :submit, "Add Member" %>
  <% end %>

</div>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

Application/app/views/users/edit.html.erb
<div id="account">
    <% provide(:title, "Edit user") %>
    <span style = "color:white"><h2>Edit Existing Organization Account</h2>
    
    <div id="bkbtn">
        <%= link_to '< Back', dashboard_path %>
    </div>

    <%= form_for @user do |f| %>
        <div id="account">
            <%= f.label :"Organization Name:" %>
            <%= f.text_field :first %><br>
        </div>

        <div id="account">
            <%= f.label :"Username:" %>
            <%= f.email_field :username %><br>
        </div>

        <div id="account">
            <%= f.label :"Password:" %>
            <%= f.password_field :password %></span><br>
        </div>

        <div id="account">
            <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>

    <% end %>
    
    <div id="account">
        <td><%= button_to 'Delete Account', '/deleteprofile', method: :delete, data: {confirm: "Are you sure?"} %></td>
    </div>

</div>

Application/app/views/users/index.html.erb
<div id="members">
  <div id="bkbtn">
    <%= link_to '< Back', dashboard_path %>
  </div>
  <p id="notice"><%= notice %></p>

  <h1>Members</h1>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>First</th>
        <th>Last</th>
        <th colspan="30"></th>
      </tr>
    </thead>

    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.username %></td>
          <td><%= member.first %></td>
          <td><%= member.last %></td>
          <td><%= button_to 'Remove Member', remove_member_path(:id => member.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


  <%= link_to 'New Member', new_member_path %>

  <br>
  <div id="memchart" class="text-center">
    <h4>Membership Growth</h4>
    <%= line_chart @members.group_by_day(:created_at).count %>
  </div>

  <br>  

</div>

Application/app/views/users/new.html.erb
<nav id="nav-header" class="text-left">
	<div id="logo" class="text-left">
        <%= image_tag "M_White_Thick.jpg", style: 'height:50px;width:30px;margin-bottom:15px;margin-right:10px;' %>
		<a id="home-btn" href="/"><span>Mporium</span></a>
	</div>
	<div id="logo"> </div>	
	<div class="dropdown show">
		<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			PRODUCTS
		</a>

		<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
			<a class="dropdown-item" href="#">Apparel</a>
			<a class="dropdown-item" href="#">Stationary</a>
			<a class="dropdown-item" href="#">Events</a>
			<a class="dropdown-item" href="#">Miscellanious</a>
		</div>
	</div>
	<div class="dropdown show">
		<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		ORGANIZATIONS
		</a>
		
		<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
			<a class="dropdown-item" href="#">Academic</a>
			<a class="dropdown-item" href="#">Arts</a>
			<a class="dropdown-item" href="#">FLOs</a>
			<a class="dropdown-item" href="#">Greek Life</a>
			<a class="dropdown-item" href="#">Health/Rec</a>
			<a class="dropdown-item" href="#">International</a>
			<a class="dropdown-item" href="#">Professional</a>
			<a class="dropdown-item" href="#">Political</a>
			<a class="dropdown-item" href="#">Religious</a>
			<a class="dropdown-item" href="#">Service</a>
			<a class="dropdown-item" href="#">Social</a>
			<a class="dropdown-item" href="#">Special Interest</a>
		</div>
	</div>
	<div id="no-drop">
		<a href="marketplace">MARKETPLACE</a>
	</div>
	<div id="no-drop">
		<a href="sign_in">LOG IN</a>
	</div>
	<div class="dropdown show">
		<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			SIGN UP
		</a>

		<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
			<a class="dropdown-item" href="#">Organization</a>
			<a class="dropdown-item" href="signup_member">Member</a>
		</div>
	</div>

</nav>

    <%= form_for @user do |f| %>

	<div class="section">
		<div class="container">
			<div class="row full-height justify-content-center">
				<div class="col-12 text-center align-self-center py-5">
					<div class="section pb-5 pt-5 pt-sm-2 text-center">
						<h1 class="mb-0 pb-3">I am trying to sign up as an ...</h1>
			          	<label for="reg-log"></label>
						<div class="card-3d-wrap mx-auto">
							<div class="card-3d-wrapper">
								<div class="card-front">
									<div class="center-wrap">
										<div class="section text-center">
											<h4 class="mb-4 pb-3">Organization</h4>
											<div class="form-group">
												<%= f.label :"Organization Name:" %>
												<%= f.text_field :first %><br><br>
												<%= f.label :"Username:" %>
												<%= f.text_field :username %><br>
                                            <br>
											</div>	
											<div class="form-group mt-2">
												<%= f.label :"Password:" %>
												<%= f.password_field :password %><br>
											</div>
                                            <br>
											 <button id="login-submit" class="container text-center btn btn-default">
                                                <span visibility: hidden><%= f.submit "Create Account"%></span>
                                                <span class="button__text" class="container text-center">Create Account</span>
                                            </button>
                            				<p class="mb-0 mt-4 text-center"><a href="#0" class="link">Forgot your password?</a></p>
											<%= link_to "Sign Up with Google", '/auth/google_oauth2?from=user', method: :post %>
				      					</div>
			      					</div>
			      				</div>
			      			</div>
			      		</div>
			      	</div>
		      	</div>
	      	</div>
	    </div>
	</div>

	   <% end %>

    <br>

	<span id="err-msg" class="container text-center">
		<% flash.each do |type, msg| %>
			<div>
				<%= msg %>
			</div>
		<% end %>
	</span>

Application/app/views/users/show.html.erb
<h1><span style = "color:white">Welcome</span></h1>
<% if logged_in? %>
    <h1><span style = "color:white">You are Logged In, <%= current_user.first %></span></h1>
    <td><%= button_to 'Show Your Products', "products#index", method: :get %></td>
    <td><%= button_to 'Add Product', "/upload", method: :get %></td>
    <td><%= button_to 'Edit Profile', '/editprofile', method: :get %></td>
    <td><%= button_to 'Delete Account', '/deleteprofile', method: :delete, data: {confirm: "Are you sure?"} %></td>
    <td><%= button_to 'Logout', logout_path, :method => :delete %></td>
<%end%>