Application/config/routes.rb
Rails.application.routes.draw do
  get "/mem_profile", to: "members#show"
  get "/edit_mem", to: "members#edit"
  delete "/delete_member", to: "members#destroy"
  delete "remove_member/:id", to: "users#remove_member", as: "remove_member"
  resources :members
  resources :products

  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get "/", to: "articles#index"

  get "/add_potential_members", to: "users#add_members"
  post "/create_new_member", to: "users#create_new_member"
  get "/signup_organization", to: "users#new"
  get "/signup_member", to: "members#new"

  post "add_to_cart/:product_id", to: "products#add_to_cart", as: 'add_to_cart'

  delete "remove_from_cart/:product_id", to: "products#remove_from_cart", as: 'remove_from_cart'

  get "view_cart", to: "products#view_cart", as: 'view_cart'

  post '/set_referral', to: "products#set_referral"

  post "/tag_marketplace", to: "products#tag_marketplace"

  post "/org_marketplace", to: "products#org_marketplace"

  post "/marketplace", to: "products#tag_marketplace"

  resources :users, only: [:new, :create, :update, :edit, :destroy, :show, :index]

  get "/welcome", to: "articles#welcome"

  get "/marketplace", to: "products#marketplace"

  root to: "products#marketplace"

  get "/dashboard", to: "dashboards#dashboard"

  get "products", to: "articles#products"
  get "/view_members", to: "users#index"
  get "profile", to: "dashboards#dashboard"
  

  get "/checkout", to: "orders#index"

  get "upload", to: "products#new"
  post "upload", to: "products#create"

  get 'editprofile', to: "users#edit"

  delete 'deleteprofile', to: "users#destroy"
  delete '/', to: "sessions#destroy"

  post :create_order, :to => 'orders#create_order'
  post :capture_order, :to => 'orders#capture_order'

  get 'tags/:tag', to: 'products#tag_index', as: :tag

  get '/auth/google_oauth2/callback' => 'sessions#omniauth'
  get '/auth/google_oauth2_member/callback' => 'sessions#omniauth_member'
  get '/auth/failure', to: redirect('/')



  resources :articles
  resources :member
  # post "/login", to: "articles#welcome"

  # post "userinfo", to: ""
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

Application/app/models/product.rb
class Product < ActiveRecord::Base
    has_one_attached :image
    validates :title, presence: true
    validates :image, attached: true
    belongs_to :user
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings



    def self.tagged_with(name)
        Tag.find_by!(name: name).products
        end

        def self.tag_counts
        Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
        end

        def tag_list
        tags.map(&:name).join(', ')
        end

        def tag_list=(names)
        self.tags = names.split(',').map do |n|
            Tag.where(name: n.strip).first_or_create!
        end
    end
   # validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
    # attr_accessor :image

end

Application/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_product, :initialize_cart, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @user = User.find_by_id(session[:id])
    @products = @user.products.all
  end

  def tag_index
    @user = User.find_by_id(session[:id])
    @tag = params[:tag]
    params[:tag] ? @products = @user.products.tagged_with(params[:tag]) : @products = @user.products.all
  end 

  def marketplace
    @tags = Tag.all
    @users = User.all
    @products = Product.order(:id).all
  end

  def initialize_cart
    session[:cart] ||= []
    session[:referral] = nil
  end

  def view_cart
    @cart_ids = session[:cart]
    @total = 0
    if @cart_ids != nil
      @cart_ids.each do |cart_id|
        @total += Product.find_by_id(cart_id).price
      end
    end

    session[:total] = @total

    @member_refer = Member.find_by_referral_code(session[:referral])
    if @member_refer != nil
      @member_refer = Member.find_by_referral_code(session[:referral]).first
    end
  end 

  def add_to_cart
    session[:cart] ||= []
    session[:cart] << params[:product_id]

    @product = Product.find_by_id(params[:product_id])
    new_quantity = @product.quantity - 1
    @product.update_attribute(:quantity, new_quantity)

    @member_refer ||= Member.find_by_referral_code(session[:referral])
    if @member_refer != nil
      new_refer = @member_refer.num_referred + 1
      @member_refer.update_attribute(:num_referred, new_refer)
    end
    redirect_to "/marketplace"
  end

  def remove_from_cart
    session[:cart].delete_at(session[:cart].index(params[:product_id]))
    @product = Product.find_by_id(params[:product_id])
    new_quantity = @product.quantity + 1
    @product.update_attribute(:quantity, new_quantity)

    @member_refer ||= Member.find_by_referral_code(session[:referral])
    if @member_refer != nil
      new_refer = @member_refer.num_referred - 1
      @member_refer.update_attribute(:num_referred, new_refer)
    end

    redirect_to "/view_cart"
  end

  def set_referral
    session[:referral] = params[:referral_code]
    redirect_to "/marketplace"
  end

  def org_marketplace
    @products = Product.where(user_id: params[:org_id])
  end

  def tag_marketplace
    @selected_tag = Tag.find_by_id(params[:tag_id]).name

    @product_ids = Tagging.where(tag_id: params[:tag_id]).pluck(:product_id)

    @products = Product.where(id: @product_ids)

    # @products = @taggings.where(@)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @user = User.find_by_id(session[:id])
    product_params = params.require(:product).permit(:title, :image, :price, :tag_list, :tag, { tag_ids: [] }, :tag_ids, :quantity)
    @product = @user.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    product_params = params.require(:product).permit(:title, :image, :price, :tag_list, :tag, { tag_ids: [] }, :tag_ids, :quantity)
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @user = User.find_by_id(session[:id])
    @product = @user.products.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def product_params
  #   params.require(:product).permit(:title, :image)
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :image, :price, :tag_list, :tag, { tag_ids: [] }, :tag_ids, :quantity)
    end
end

Application/app/helpers/products_helper.rb
module ProductsHelper
end

Application/app/views/products/_form.html.erb
<%= simple_form_for @product do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %> 
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <%= form.input :tag_ids, as: :select, collection: Tag.order(:name), label_method: :name, input_html: {multiple: true} %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Application/app/views/products/add_to_cart.html.erb
<h1>Hello</h1>

Application/app/views/products/edit.html.erb
<div id="index">
    <div id="bkbtn">
        <%= link_to '< Back', products_path %>
    </div>

    <h1>Editing Product</h1>

    <%= render 'form', product: @product %>
    
</div>

Application/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div id="marketplace" class="mx-auto">
  <div id="bkbtn">
    <%= link_to '< Back', dashboard_path %>
  </div>

  <h1>Products</h1>

  
    <tbody>
      <% @products.each do |product| %>
        <div id="prodedit" class="card">
       
            <div id="prodinfo">
              <%= product.title %>
            </div>
            <div id="prodinfo">
              <%= image_tag product.image.variant(
                format: :png,
                resize_and_pad: [200, 200, gravity: 'north', background: :transparent]
              ) %>
            </div>
            <div id="prodinfo">
              <%= "Price: $" + product.price.to_s %>
            </div>
            <div id="prodinfo">
              <%= button_to 'Edit Product', edit_product_path(product), method: :get %>
            </div>
            <div id="prodinfo">
              <%= button_to 'Delete Product', product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
            </div>

         
        </div>
      <% end %> 

      <div id="prodedit" class="card">
        <div id="prodinfo">
          <h5>Add New Product</h5>
        </div>
        <div id="prodadd">
          <%= link_to '+', upload_path %>
        </div>
      </div>

    </tbody>

  <br>

  

</div>

Application/app/views/products/marketplace.html.erb
<nav id="nav-header" class="text-left">
	<div id="logo" class="text-left">
		<%= image_tag "M_White_Thick.jpg", style: 'height:50px;width:30px;margin-bottom:15px;margin-right:10px;' %>
		<a id="home-btn" href="/"><span>Mporium</span></a>
	</div>
	<div id="logo"> </div>	
	<div class="dropdown">
		<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
			PRODUCTS
		</a>

		<div class="dropdown-menu" aria-labelledby="dropdownMenuLink" role="button">
			<%= form_with(url: "/tag_marketplace") do |f| %>
				<%= f.select :tag_id, @tags.map { |t| [t.name, t.id] }, include_blank: true %>
				<%= f.submit %>
			<% end %>
		</div>
	</div>
	<div class="dropdown">
		<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
		ORGANIZATIONS
		</a>
		
		<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
			<%= form_with(url: "/org_marketplace") do |f| %>
				<%= f.select :org_id, @users.map { |u| [u.first, u.id] }, include_blank: true %>
				<%= f.submit %>
			<% end %>
		</div>
	</div>
	<div id="no-drop">
		<a href="marketplace">MARKETPLACE</a>
	</div>
	<div id="no-drop">
		<a href="sign_in">LOG IN</a>
	</div>
	<div class="dropdown">
		<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			SIGN UP
		</a>

		<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
			<a class="dropdown-item" href="signup_organization">Organization</a>
			<a class="dropdown-item" href="signup_member">Member</a>
		</div>
	</div>

</nav>








<div id="marketplace">
	<h1>MARKETPLACE</h1>
	<%= link_to 'View Cart', view_cart_path %>
	<%= simple_form_for :view_cart_path, :url => "/set_referral", :method => :post do |f| %>
	<%= f.input :referral_code, input_html: { name: "referral_code" } %>
	<%= f.button :submit, "Set referral code" %>
<% end %>
</div>


<br>
<div id="marketplace" class="mx-auto">
	<span style = "color:white">
	<tbody>
		<% @products.each do |product| %>
		<div class="card">
		
				<div id="prodinfo">
					<span style="color:black"><%= product.title %></span>
				</div>
				<div id="prodinfo">
					<%= image_tag product.image.variant(
						format: :png,
						resize_and_pad: [200, 200, gravity: 'north', background: :transparent]
					) %>
				</div>
				<div id="prodinfo">
					<span style="color:black"><%= "Price: $" + product.price.to_s %></span>
				</div>
			
			<%# <a href="checkout" class="button1 mx-auto">Add to Cart</a> %>
			<%= button_to 'Add to Cart', add_to_cart_path(product.id), method: :post %>
			<br>
			</div>
		<% end %>
	</tbody>
	</span>
</div>

Application/app/views/products/new.html.erb
<div id="index">
    <div id="bkbtn">
        <%= link_to '< Back', products_path %>
    </div>

    <h1>Create New Product</h1>

    <%= render 'form', product: @product %>

   
</div>

Application/app/views/products/org_marketplace.html.erb
<div id="marketplace">
	<h1>Products sold by <%= User.find_by_id(params[:org_id]).first %></h1>
</div>

<br>
<%= link_to 'Back to Marketplace', "/marketplace" %> 
<br>

<% @products.each do |product| %>
	<div class="card">
	
			<div id="prodinfo">
				<span style="color:black"><%= product.title %></span>
			</div>
			<div id="prodinfo">
				<%= image_tag product.image.variant(
					format: :png,
					resize_and_pad: [200, 200, gravity: 'north', background: :transparent]
				) %>
			</div>
			<div id="prodinfo">
				<span style="color:black"><%= "Price: $" + product.price.to_s %></span>
			</div>
		
		<a href="checkout" class="button1 mx-auto">Add to Cart</a>
		<br>
	</div>
<% end %>

Application/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div id="index">
  <p>
    <strong>Title:</strong>
    <%= @product.title %>
  </p>

  <p>
    <% if @product.image.attached? %>
      <%= image_tag @product.image.variant(
        format: :png,
        resize_and_pad: [200, 200, gravity: 'north', background: :transparent]
      ) %>
    <% end %>
  </p>

    <strong>Price:</strong>
    <%= "$" + @product.price.to_s %>

    <strong>Quantity: <%= @product.quantity %></strong>

    <p><small>Tags: <%= raw @product.tags.map(&:name).map { |t| link_to t, tag_path(t) }.join(', ') %></small></p>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

Application/app/views/products/tag_index.html.erb
<p id="notice"><%= notice %></p>

<div id="index">
  <h1>Products with the tag: <%=@tag%></h1>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= button_to 'Show Product', product, method: :get %></td>
          <td><%= button_to 'Edit Product', edit_product_path(product), method: :get %></td>
          <td><%= button_to 'Delete Product', product_path(product), method: :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
      <% end %> 
    </tbody>
  </table>
</div>
<br>

<%= link_to 'New Product', new_product_path %>

<br>

<%= link_to 'Back', dashboard_path %>

Application/app/views/products/tag_marketplace.html.erb
<div id="marketplace">
	<h1>Marketplace with <%= @selected_tag %></h1>
</div>

<br>
<%= link_to 'Back to Marketplace', "/marketplace" %> 
<br>

<% @products.each do |product| %>
	<div class="card">
	
			<div id="prodinfo">
				<span style="color:black"><%= product.title %></span>
			</div>
			<div id="prodinfo">
				<%= image_tag product.image.variant(
					format: :png,
					resize_and_pad: [200, 200, gravity: 'north', background: :transparent]
				) %>
			</div>
			<div id="prodinfo">
				<span style="color:black"><%= "Price: $" + product.price.to_s %></span>
			</div>
		
		<a href="checkout" class="button1 mx-auto">Add to Cart</a>
		<br>
	</div>
<% end %>

Application/app/views/products/view_cart.html.erb
<p><span style= "color:white">Your Cart:</span></p>

<p><span style= "color:white">You are referred by: <%= @member_refer %></span></p>

<div id="marketplace" class="mx-auto">
	<span style = "color:white">
	<tbody>
		<% if @cart_ids != nil %>
			<% @cart_ids.each do |cart_id| %>
				<div class="card">
					<div id="prodinfo">
						<span style="color:black"><%= Product.find_by_id(cart_id).title %></span>
					</div>
					<div id="prodinfo">
						<%= image_tag Product.find_by_id(cart_id).image.variant(
							format: :png,
							resize_and_pad: [200, 200, gravity: 'north', background: :transparent]
						) %>
					</div>
					<div id="prodinfo">
						<span style="color:black"><%= "Price: $" + Product.find_by_id(cart_id).price.to_s %></span>
					</div>

					<%= button_to 'Remove From Cart', remove_from_cart_path(cart_id), method: :delete %>
				</div>
			<% end %>
		<% else %>
			<h1>Your cart is empty.</h1>
		<% end %>
	</tbody>
	<br>
	<p><span style= "color:white">Total Cost: <%= @total %></span></p>
	<br>

	<%# <a href="checkout" class="button1 mx-auto">Checkout</a> %>
	<%= link_to "Checkout", '/checkout' %>
	</span>
</div>